language: node_js
node_js:
  - "6"

install:
  - npm install
  - npm install -g elm
  - elm-package install -y

script:
  - rm -rf public
  - mkdir public
  - elm-make Main.elm --output=public/index.html

deploy:
  provider: surge
  project: ./public/
  domain: six-shooter.surge.sh
  skip_cleanup: true
